In [1]:
# import
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)
from pydataset import data

In [2]:
# obtaining cars data
from pydataset import data
mtcars = data('mtcars')
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [3]:
# how many entries that contain each unique value
mtcars["gear"].value_counts()

gear
3    15
4    12
5     5
Name: count, dtype: int64

In [4]:
# making a fresh copy for backup
mtcars_edit = mtcars.copy()

In [5]:
mtcars_edit["am"] = mtcars_edit["am"].map({0:"auto", 1:"manual"})
mtcars_edit.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,manual,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,manual,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,manual,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,auto,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,auto,3,2

In [6]:
mtcars["hp"].sort_values()

Honda Civic             52
Merc 240D               62
Toyota Corolla          65
Fiat X1-9               66
Fiat 128                66
Porsche 914-2           91
Datsun 710              93
Merc 230                95
Toyota Corona           97
Valiant                105
Volvo 142E             109
Mazda RX4              110
Mazda RX4 Wag          110
Hornet 4 Drive         110
Lotus Europa           113
Merc 280C              123
Merc 280               123
Dodge Challenger       150
AMC Javelin            150
Ferrari Dino           175
Pontiac Firebird       175
Hornet Sportabout      175
Merc 450SL             180
Merc 450SLC            180
Merc 450SE             180
Cadillac Fleetwood     205
Lincoln Continental    215
Chrysler Imperial      230
Camaro Z28             245
Duster 360             245
Ford Pantera L         264
Maserati Bora          335
Name: hp, dtype: int64

In [7]:
mtcars_hp = mtcars.copy()
bins = [0, 100, 180, 250, mtcars['hp'].max()]
labels = ['Very Low', 'Low', 'Medium', 'High']
mtcars_hp['hp level'] = pd.cut(mtcars['hp'], bins=bins, labels=labels, include_lowest=True)

In [8]:
mtcars_hp.head(mtcars.shape[0])

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,hp level
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,Low
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,Low
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,Very Low
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,Low
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,Low
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1,Low
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4,Medium
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2,Very Low
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2,Very Low
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4,Low
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4,Low
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3,Low
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3,Low
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3,Low
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4,Medium
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4,Medium
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4,Medium
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1,Very Low
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2,Very Low
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1,Very Low
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1,Very Low
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2,Low
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2,Low
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4,Medium
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2,Low
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1,Very Low
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2,Very Low
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2,Low
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4,High
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6,Low
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8,High
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2,Low

In [22]:
mtcars_cat = mtcars_hp.copy()
mtcars_cat = mtcars_cat.astype({'cyl':'category', 'vs':'category', 'carb':'category', 'am':'category', 'gear':'category'})
mtcars_cat.head(mtcars.shape[0])

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,hp level
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,Low
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,Low
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,Very Low
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,Low
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,Low
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1,Low
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4,Medium
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2,Very Low
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2,Very Low
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4,Low
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4,Low
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3,Low
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3,Low
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3,Low
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4,Medium
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4,Medium
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4,Medium
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1,Very Low
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2,Very Low
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1,Very Low
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1,Very Low
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2,Low
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2,Low
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4,Medium
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2,Low
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1,Very Low
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2,Very Low
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2,Low
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4,High
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6,Low
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8,High
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2,Low

In [23]:
mtcars_cat.describe()

             mpg        disp          hp       drat         wt       qsec
count  32.000000   32.000000   32.000000  32.000000  32.000000  32.000000
mean   20.090625  230.721875  146.687500   3.596563   3.217250  17.848750
std     6.026948  123.938694   68.562868   0.534679   0.978457   1.786943
min    10.400000   71.100000   52.000000   2.760000   1.513000  14.500000
25%    15.425000  120.825000   96.500000   3.080000   2.581250  16.892500
50%    19.200000  196.300000  123.000000   3.695000   3.325000  17.710000
75%    22.800000  326.000000  180.000000   3.920000   3.610000  18.900000
max    33.900000  472.000000  335.000000   4.930000   5.424000  22.900000

In [21]:
mtcars_cat.dtypes

mpg          float64
cyl         category
disp         float64
hp             int64
drat         float64
wt           float64
qsec         float64
vs          category
am          category
gear        category
carb        category
hp level    category
dtype: object

In [26]:
mtcars[mtcars['mpg'] > 30].sort_values('mpg', ascending=False)

                 mpg  cyl  disp   hp  drat     wt   qsec  vs  am  gear  carb
Toyota Corolla  33.9    4  71.1   65  4.22  1.835  19.90   1   1     4     1
Fiat 128        32.4    4  78.7   66  4.08  2.200  19.47   1   1     4     1
Honda Civic     30.4    4  75.7   52  4.93  1.615  18.52   1   1     4     2
Lotus Europa    30.4    4  95.1  113  3.77  1.513  16.90   1   1     5     2