### Pandas
- https://pandas.pydata.org/
- library or set of modules available for data manipulation

In [1]:
import pandas as pd  #pd is an alias for pandas

In [2]:
#pd.

In [3]:
# Set Pandas options for wrapping
pd.set_option('display.max_columns', None)   # Show all columns
pd.set_option('display.width', 100)          # Set line width before wrapping
pd.set_option('display.max_colwidth', None)  # Don't truncate text

In [5]:
from pydataset import data  #load library of pydataset and import mtcars data from it
mtcars = data('mtcars')
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [16]:
type(mtcars)

pandas.DataFrame

In [ ]:
#pd.Dat # after dot(.) press tab to get functions 
mtcars.explode

In [ ]:
#?pd.DataFrame.head

In [ ]:
#help(pd.DataFrame.head)

In [ ]:
mtcars.head(n=3)

## Functions in Pandas
- Understanding Data
    - type  # type of object
    - shape # rows & cols in data
    - columns # column names
    - dtypes  # datatype 
    - info()  # datatypes & non-null counts
    - sample(x) # randon x rows
    - head(x) # first x rows
    - tail(x) # last x rows
- Summary Statistics
    - describe()  #summary stats for numeric cols
    - describe(include='all')  #summary stats for all cols
    - mtcars.nunique() #count of unique values per column
    - value_counts()  # freq count for a series
- Missing/Duplicates
    -  isnull().sum()   # missing value count per cols
    -  notnull().sum()  # non missing value count
    -  duplicated(().sum() # count of duplicate rows
- View Specific Col/ Row
    -  ['col_name']   # single column
    -  [['col1','col2']] # multiple columns
    -  iloc[0]   #1st row by index position
    -  loc[0] #1st row by label
    -  iloc[0:5]   # first 5 rows
-  Basic Data Insights
    -  corr(numeric_only=True)  #correlation matrix (numeric only)
    -  mean(numeric_only=True)   #mean of numeric cols
    -  mode().iloc(0) #most frequent values
    -  median(numeric_only=True) # median of numeric cols

In [17]:
type(mtcars)  #type of object

pandas.DataFrame

In [18]:
mtcars.head() #first 5 rows of mtcars data set  (which is impported from pydataset library)

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [19]:
mtcars.tail(4) #Last 4 rows from mtcars dataset

                 mpg  cyl   disp   hp  drat    wt  qsec  vs  am  gear  carb
Ford Pantera L  15.8    8  351.0  264  4.22  3.17  14.5   0   1     5     4
Ferrari Dino    19.7    6  145.0  175  3.62  2.77  15.5   0   1     5     6
Maserati Bora   15.0    8  301.0  335  3.54  3.57  14.6   0   1     5     8
Volvo 142E      21.4    4  121.0  109  4.11  2.78  18.6   1   1     4     2

In [30]:
mtcars.sample(3)  #any 3 row on sampling / random

                mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Merc 280C      17.8    6  167.6  123  3.92  3.440  18.90   1   0     4     4
Ferrari Dino   19.7    6  145.0  175  3.62  2.770  15.50   0   1     5     6
Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4

In [21]:
mtcars.shape #rows , columns - structure

(32, 11)

In [31]:
mtcars.columns # title, names of columns

Index(['mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear',
       'carb'],
      dtype='str')

In [32]:
mtcars.info() # info about dataset, every col - non-null , data type; float -  decimal; int- without decimal; 64 - bit
#10020202020.222

<class 'pandas.DataFrame'>
Index: 32 entries, Mazda RX4 to Volvo 142E
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   mpg     32 non-null     float64
 1   cyl     32 non-null     int64
 2   disp    32 non-null     float64
 3   hp      32 non-null     int64
 4   drat    32 non-null     float64
 5   wt      32 non-null     float64
 6   qsec    32 non-null     float64
 7   vs      32 non-null     int64
 8   am      32 non-null     int64
 9   gear    32 non-null     int64
 10  carb    32 non-null     int64
dtypes: float64(5), int64(6)
memory usage: 4.0+ KB

In [33]:
mtcars.dtypes #column names and types

mpg     float64
cyl       int64
disp    float64
hp        int64
drat    float64
wt      float64
qsec    float64
vs        int64
am        int64
gear      int64
carb      int64
dtype: object

In [34]:
mtcars.index

Index(['Mazda RX4', 'Mazda RX4 Wag', 'Datsun 710', 'Hornet 4 Drive',
       'Hornet Sportabout', 'Valiant', 'Duster 360', 'Merc 240D', 'Merc 230',
       'Merc 280', 'Merc 280C', 'Merc 450SE', 'Merc 450SL', 'Merc 450SLC',
       'Cadillac Fleetwood', 'Lincoln Continental', 'Chrysler Imperial',
       'Fiat 128', 'Honda Civic', 'Toyota Corolla', 'Toyota Corona',
       'Dodge Challenger', 'AMC Javelin', 'Camaro Z28', 'Pontiac Firebird',
       'Fiat X1-9', 'Porsche 914-2', 'Lotus Europa', 'Ford Pantera L',
       'Ferrari Dino', 'Maserati Bora', 'Volvo 142E'],
      dtype='str')

In [35]:
mtcars.head(2)

                mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Mazda RX4      21.0    6  160.0  110   3.9  2.620  16.46   0   1     4     4
Mazda RX4 Wag  21.0    6  160.0  110   3.9  2.875  17.02   0   1     4     4

## Summary

In [ ]:
mtcars.describe() #for all numeric cols - count, min, max, mean, std dev, Q1, Q2, Q3

In [ ]:
mtcars.mpg.describe()

In [ ]:
mtcars.describe(include='all')  #for all types of columns

In [ ]:
mtcars.cyl.value_counts() # count of each cyl type cars

In [ ]:
mtcars.nunique()   # count of unique values in each col

In [ ]:
mtcars.gear.value_counts()

In [ ]:
mtcars['am'].value_counts()  #by tx

## Read/ Write - CSV/ EXCEL
-

## Read/write to CSV

In [ ]:
mtcars.to_csv('mtcarsdata.csv', index=False)

In [ ]:
mtcars2 = pd.read_csv('mtcarsdata.csv')
mtcars2.head(2)

## read/write to Excel
- https://pandas.pydata.org/docs/reference/api/pandas.read_excel.html
- https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_excel.html

In [ ]:
#?mtcars.to_excel

In [ ]:
mtcars.to_excel('mtcarsdata2.xlsx', index=False)
# index - rownames get stored if index -T

In [ ]:
mtcars3 = pd.read_excel('mtcarsdata2.xlsx', sheet_name=0)
mtcars3.head(5)

In [ ]:
#mtcars.to_excel('mtcarsdata2.xlsx', index=True) - same mtcars.to_excel('mtcarsdata2.xlsx')

## Missing
- df.isnull() - missing values
- https://pandas.pydata.org/docs/reference/api/pandas.isnull.html
- df.notnull()  - not null values

In [ ]:
mtcars.shape  #rows, cols

In [ ]:
mtcars.isnull().sum().sum() # missing values in full Data Frame

In [ ]:
mtcars.isnull().head()  # False -> 0, True - 1

In [ ]:
mtcars.isnull().sum(axis=0)  #counting missing values, columns wise, axis=0 (Columns)

In [ ]:
mtcars.isnull().sum(axis=1)  # count missing values, rowwise , axis=1 (Rows)

In [ ]:
# Opposite of isnull or notnull
mtcars.notnull().sum(axis=0) # for each column, count non-missing values, 32

In [ ]:
mtcars.notnull().sum(axis=1)  # for each row, count of non-missing values, 11

In [ ]:
32 * 11

In [ ]:
mtcars.notnull().sum(axis=0).sum()

In [ ]:
mtcars.head()

In [ ]:
mtcars.max(axis=0)

In [ ]:
mtcars.notnull().sum(axis=0).sum() # 32 x 11

# Check for Duplicates
- duplicated()  #check for duplicate rows
- https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.drop_duplicates.html

In [ ]:
#?mtcars.duplicated
mtcars = data('mtcars')
mtcars.head(2)

In [ ]:
mtcars2 = mtcars.copy().reset_index().rename(columns={'index':'car'})  #duplicate, reset_index (rownames to column by index), rename by index to car
mtcars2.head()

In [ ]:
mtcars2.shape   #car - 12

### simulate duplicate rows

In [ ]:
mtcars2[mtcars2['car'] == 'Mazda RX4']  #all cars with name of Mazda RX4

In [ ]:
mazda2 = mtcars2[mtcars2['car'] == 'Mazda RX4']
datson2 = mtcars2[mtcars2['car'] == 'Datsun 710']
# copied mazda and datson car in variable/ row

In [ ]:
mtcars_dup = pd.concat([mtcars2, mazda2, datson2, mazda2], ignore_index=True) # 2 more cars Mazda, 1 more car for Datson
mtcars_dup #.sort_values('car')

In [ ]:
mtcars_dup.shape

In [ ]:
mtcars_dup[mtcars_dup['car'] == 'Mazda RX4']
#duplicate cars - 3 cars of Mazda RX4

In [ ]:
mtcars_dup[mtcars_dup['car'] == 'Datsun 710']

In [ ]:
mtcars_dup.duplicated().sum()  #duplicate rows - 3

In [ ]:
#mtcars_dup.duplicated(subset = ['gear']).sum()

In [ ]:
#mtcars_dup.duplicated(keep=False)  #mark all duplicates

In [ ]:
mtcars_dup.drop_duplicates()

In [ ]:
#?mtcars_dup.drop_duplicates

In [ ]:
mtcars_dup.drop_duplicates(keep='first')  #first

In [ ]:
mtcars_dup.drop_duplicates(keep='last')

In [ ]:
mtcars_dup.drop_duplicates(keep=False)  #remove duplicates

In [ ]:
mtcars_dup[mtcars_dup.duplicated(subset = ['vs','am','gear','carb'])].sort_values(['vs','am','gear','carb'])

In [ ]:
mtcars[mtcars.duplicated(subset = ['gear','am','cyl','carb'], keep=False)].sort_values(by=['gear','am','cyl','carb'])
#keep=False marks all occurrences of duplicates, not just the later ones.

In [ ]:
mtcars_dup[~ mtcars_dup.duplicated(subset = ['gear','am','cyl','carb'], keep=False)].sort_values(by=['gear','am','cyl','carb'])
# non duplicates wrt column in subjset

In [ ]:
mtcars_dup.drop_duplicates(subset = ['gear','am','cyl','carb'], inplace=False)
#remove duplicates by selected columns

### View rows/ columns

In [ ]:
mtcars['mpg'].head()

In [ ]:
mtcars.columns

In [ ]:
mtcars[['wt','mpg']].tail()

In [ ]:
mtcars.iloc[0] #1st row

In [ ]:
mtcars.iloc[3:5]  #3rd to 5th row, all columns

In [ ]:
mtcars.iloc[[0,4]]  #index position

In [ ]:
mtcars.iloc[0:4]  # range of index position,   x:y  : from x to y-1

In [ ]:
mtcars.head(5)

In [ ]:
mtcars.loc['Datsun 710']  #row by rowname

In [ ]:
carlist = ['Mazda RX4','Datsun 710']
#mtcars.loc[['Mazda RX4','Datsun 710']] #row by rowname
mtcars.loc[carlist]

In [ ]:
mtcars.iloc[[0,2]]

In [ ]:
mtcars.columns

In [ ]:
mtcars.loc[:, 'mpg':'wt'].head()  # from mpg to wt columns by name

In [ ]:
mandalCarList = ['Mazda RX4','Datsun 710', 'Hornet 4 Drive']  #list of cars
print(mandalCarList)
mtcars.loc[mandalCarList, 'mpg':'wt'].head()  # row by names, col by names

In [ ]:
mtcars.loc[['Mazda RX4','Datsun 710', 'Hornet 4 Drive'], 'mpg':'wt'].head()

In [ ]:
mtcars.index

In [ ]:
mtcars.iloc[:, 3:8].head()

In [ ]:
mtcars.iloc[1:10, [3,6,9,10]] #.head()  #4th, 7th, 10th, 11th col

In [ ]:
mtcars.iloc[0:3, [3,6,9,10]]

In [ ]:
mtcars.iloc[[0,4,31], [3,6,9,10]].head()  #4th, 7th, 10th, 11th col with 1st, 5th, 32th row

In [ ]:
mtcars.columns

## Summmary
- iloc - locating an item by index
- missing value - isnull, notnull
- duplicate - locating, remove
- Read/ Write to CSV, Excel  : df.to_csv, pd.read_csv  . excel
- filter specific columns or rows
- items in columns - concate - rows
- shape, head, tail, columns, str, help, ?
- import data from pydataset
- range

## END HERE
- Go To Advanced
- Mandal & Suroor - help students with GitHub, Anaconda, *
- Asssignment, Task